### PR TITLE
Read external rdfa data

### LINKED ISSUE #7: Generate Entities from our own schema extending schema.org
Hi,

I don't know if these is an issue or a feature not already implemented.

I have for example, a vocabulary that extends schema.org vocabulary

File data/schema.rdfa
```html
<div typeof="rdfs:Class" resource="http://example/Language">
      <span class="h" property="rdfs:label">Language</span>
      <span>Subclass of: <a property="rdfs:subClassOf" href="http://schema.org/Language">Language</a></span>
      <span property="rdfs:comment"></span>
</div>

<div typeof="rdfs:Property" resource="http://example/locale">
    <span property="rdfs:label">locale</span>
    <span property="rdfs:range">Text</span>
    <span property="rdfs:comment">locale of the language</span>
    <span property="rdfs:domain">http://example/Language</span>
</div>
```

Here is the yml file to generate my entities
```yml
rdfa:
   - http://schema.org/docs/schema_org_rdfa.html
   - data/schema.rdfa
annotationGenerators:
    - SchemaOrgModel\AnnotationGenerator\PhpDocAnnotationGenerator
    - SchemaOrgModel\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - SchemaOrgModel\AnnotationGenerator\ConstraintAnnotationGenerator
    - SchemaOrgModel\AnnotationGenerator\DunglasJsonLdApiAnnotationGenerator
namespaces:
  entity: AppBundle\Entity
types:
  http://example/Language:
    properties:
      name: ~
      locale: ~
```

I execute : 
```bash
./bin/schema generate-types src app/config/schema.yml -vvv
[critical] Type "http://example/Language" cannot be found.
```

So, what is the problem ? 
php-schema doesn't support extending another schema yet ? 
And the solution is to generate entities from schema.org only and modify them after ?

Thanks

### PR DESCRIPTION
**Pull request by ahlee2326**
fixes #7

### CODE REVIEW

**Comment by dunglas** [comment]
Looks good! Can you squash your commits?

**Comment by dunglas** [comment]
Can you also add a line in the doc explaining how to use this feature?

**Comment by ahlee2326** [comment]
Updated.

**Comment by dunglas** [comment]
Thank you @ahlee2326

**Comment by ahlee2326** [comment]
@dunglas I think this is not usable and should revert back to previous commit as there are a lots more problems while using this and the entire design is not supported for this purpose yet, in order to making this to work, lots of restructuring is required. So I personally think this should hold aside and revert back to the previous commit.

**Comment by dunglas** [comment]
Reverted in #13. Do you plan to take a further look to that feature?

**Pull request merged**
